SPDX-PackageDownloadLocation = "https://github.com/SAP/invoke-plugin-for-pylint"
SPDX-PackageName = "invoke-plugin-for-pylint"
SPDX-PackageSupplier = "kai.harder@sap.com"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "2026 SAP SE or an SAP affiliate company and invoke-plugin-for-pylint contributors"
SPDX-License-Identifier = "Apache-2.0"
path = "**"
precedence = "aggregate"
